package com.bs.beyond.entity;

public class BUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.user_id
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.user_name
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_user.password
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.user_id
     *
     * @return the value of b_user.user_id
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.user_id
     *
     * @param userId the value for b_user.user_id
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.user_name
     *
     * @return the value of b_user.user_name
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.user_name
     *
     * @param userName the value for b_user.user_name
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_user.password
     *
     * @return the value of b_user.password
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_user.password
     *
     * @param password the value for b_user.password
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}