package com.bs.beyond.dao;

import com.bs.beyond.entity.BUser;

public interface BUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    int insert(BUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    int insertSelective(BUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    BUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    int updateByPrimaryKeySelective(BUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Wed Nov 30 14:54:41 CST 2016
     */
    int updateByPrimaryKey(BUser record);
}