package com.bs.beyond.dao;

import com.bs.beyond.entity.BUser;

public interface BUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Thu Dec 01 17:07:44 CST 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Thu Dec 01 17:07:44 CST 2016
     */
    int insert(BUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Thu Dec 01 17:07:44 CST 2016
     */
    int insertSelective(BUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Thu Dec 01 17:07:44 CST 2016
     */
    BUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Thu Dec 01 17:07:44 CST 2016
     */
    int updateByPrimaryKeySelective(BUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_user
     *
     * @mbg.generated Thu Dec 01 17:07:44 CST 2016
     */
    int updateByPrimaryKey(BUser record);
}